spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/unistay
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
api.security.secret=MINHA_CHAVE_SECRETA_SUPER_SEGURA
